### ISSUE TITLE
Deleted page are not removed when site is published

### ISSUE THREAD

**Issue by icaraps** [adobe/aio-cli-plugin-doc#10]
## Problem
If a page is added and the site is deployed to Azure, then deleted and the site is re-deployed, the page is still there. 

## Expected behavior
Deleted page should be deleted once the site is deployed.

**Comment by shazron** [comment]
For GH Pages, there is a `CLEAN` option:
https://github.com/JamesIves/github-pages-deploy-action

**Comment by shazron** [comment]
For the Azure deploy, there is an option `remove-existing-files` that wasn't in the README:
https://github.com/tibor19/static-website-deploy/blob/f32720a4f9e8fa18f54587fad4b6fb3c5e202631/index.js#L56
